image: python:3.11
pipelines:
  default:
    - step:
        name: Testing with pytest
        script:
          - pip install -r requirements.txt
          - pytest .
    - step:
        name: Format Checking with black
        script:
          - pip install -r requirements.txt
          - black --check .
    - step:
        name: Type checking with mypy
        script:
          - pip install -r requirements.txt
          - mypy .
